### ISSUE TITLE
Can we use this library for glb and gltf formates

### ISSUE THREAD

**Issue by prabakaranr** [awesome7/XamAR#79]

**Comment by miki-bgd** [comment]
Haven't tested it myself, but should be possible. This is also on our to-do list.

Refer to this post: https://github.com/xamarin/XamarinComponents/issues/833#issuecomment-911909326 
And then you need custom factory which will load it: https://github.com/awesome7/XamAR 

PS. And don't forget to manage async invoke from sync code, there are multiple solutions on the internet.

PS2. And please feel free to share your results.

Miki
